name: Build and Deploy node Python Flask app to Azure
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "testpythonapp123"    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "Application"      # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.5.9'                # set this to the python version to use
  RESOURCEGROUPNAME: "testpythonapp123-rg"
  LOCATION: "South Central US"
  HOSTINGPLANNAME: "testpythonapp123-plan"
  APPINSIGHTLOCATION: "South Central US"
  SKU: "S1 Standard"
  DATABASEACCOUNTID: ""
  DATABASEACCOUNTLOCATION: ""

jobs:
  build:
    name: Build and Run tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        node-version: ${{ env.PYTHON_VERSION }}
    - name: Setup Virtual environment and installing dependancies
      continue-on-error: false
      run: |
        py -m pip install --user virtualenv
        py -m venv env
        .\env\Scripts\activate
        pip install -r Application/requirements.txt
    - name: Install Dependancies for testing
      continue-on-error: false
      run: |
        pip install -r Application/requirements.txt
    - name: Pytest
      continue-on-error: false
      run: |
        pip install pytest && pytest Tests/unit_tests --junitxml=../TestResults/test-results.xml && pip install pycmd && py.cleanup Tests/
    - name: Creating artifact directories
      run: |
        mkdir buildartifacts
        mkdir testartifacts
        mkdir deploymenttemplates
    # Archieve build artifact
    - name: Archive Application
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./buildartifacts/Application.zip ./Application
    # uploading application to build artifact
    - name: Upload Application to Build Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: buildartifacts
        path: buildartifacts
    # Archive Tests        
    - name: Archive Tests
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./testartifacts/Tests.zip ./Tests
    # uploading Tests to artifact
    - name: Upload Tests to Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: testartifacts
        path: testartifacts
    # Archive Arm templates
    - name: Archive ArmTemplates
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./deploymenttemplates/armtemplates.zip ./ArmTemplates
    # uploading Arm Templates to artifacts
    - name: Upload Arm templates to Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: deploymenttemplates
        path: deploymenttemplates
  Deploy:
    name: Deploy to azure web app
    needs: build
    runs-on: ubuntu-latest
    steps:
    # Downloading build artifact
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: buildartifacts
        path: buildartifacts
    # Uzipping build artifacts
    - name: unzipping build artifact
      uses: montudor/action-zip@v0.1.0
      with:
       args: unzip -qq ./buildartifacts/Application.zip -d .
  # Downloading Arm Templates
    - name: Download an Arm template
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: deploymenttemplates
        path: deploymenttemplates
    # Uzipping Arm template directory
    - name: unzipping arm artifact
      uses: montudor/action-zip@v0.1.0
      with:
       args: unzip -qq ./deploymenttemplates/armtemplates.zip -d .
    # login to azure
    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy Arm template
    - name: Deploy ARM Template
      uses: azure/CLI@v1
      continue-on-error: false
      with:
        inlineScript: |
          az group create --name "${{ env.RESOURCEGROUPNAME }}" --location "${{ env.LOCATION }}"
          az deployment group create --resource-group "${{ env.RESOURCEGROUPNAME }}" --template-file ./ArmTemplates/windows-webapp-template.json --parameters webAppName="${{ env.AZURE_WEBAPP_NAME }}" hostingPlanName="${{ env.HOSTINGPLANNAME }}" appInsightsLocation="${{ env.APPINSIGHTLOCATION }}" sku="${{ env.SKU }}"
    # Deploy web app
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  FunctionalTests:
    name: Run Functional tests
    runs-on: windows-latest
    needs: Deploy
    steps:
    # Run functional tests
    - name: Run Functional tests
      continue-on-error: false
      run: |
        $Path = $env:TEMP; $Installer = "chrome_installer.exe"; Invoke-WebRequest "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile $Path$Installer; Start-Process -FilePath $Path$Installer -Args "/silent /install" -Verb RunAs -Wait; Remove-Item $Path$Installer
        Invoke-WebRequest https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_win32.zip -outFile chromedriver.zip
        Expand-Archive -Path chromedriver.zip
        Remove-Item chromedriver.zip
        pip install selenium && pip install pytest && pytest Tests/functional_tests/ --webAppUrl=${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/ --junitxml=TestResults/test-results.xml
