name: Build and Deploy node Python Flask app to Azure
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "testpythonapp123"    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "Application"      # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.7.5'                # set this to the python version to use
  RESOURCEGROUPNAME: "testpythonapp123-rg"
  LOCATION: "South Central US"
  HOSTINGPLANNAME: "testpythonapp123-plan"
  APPINSIGHTLOCATION: "South Central US"
  SKU: "S1 Standard"
  DATABASEACCOUNTID: ""
  DATABASEACCOUNTLOCATION: ""

jobs:
  Deploy:
    name: Deploy to azure web app
    runs-on: ubuntu-latest
    steps:
    # Azure Login
    - name: Azure Login
      run:
        echo ${{ secrets.AZURE_CREDENTIALS }}
